language: android

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.10

jdk:
  - oraclejdk8

android:
  components:
   - tools
   - build-tools-23.0.2
   - android-23
   - extra-android-m2repository
  licenses:
   - android-sdk-license-.+

script: ./gradlew clean build
